### ISSUE TITLE
Problems running example on Windows

### ISSUE THREAD

**Issue by TysonKlein** [ecbush/xenoGI#1]
I've installed all dependencies (NCBI Blast+, Biopython, Parasail, etc.) with python version 3.6.4.
I have tried running the example on my windows 10 system through command prompt, and I get this traceback error:

Traceback (most recent call last):
  File "../parseGenbank.py", line 19, in <module>
    genbank.parseGenbank(paramD['geneOrderFN'],paramD['redundProtsFN'],paramD['geneInfoFN'],fastaDir,genbankFileList,fileNameMapD)
  File "C:\Users\Nicole\Documents\XenoGI\xenoGI-master\genbank.py", line 49, in parseGenbank
    speciesName = fileNameMapD[genbankName]
KeyError: 'ncbi\\GCA_000005845.2_ASM584v2_genomic.gbff'

I have not altered anything with the example and all the dependencies are functioning fine. Is this because xenoGI is designed for a platform other than Windows? I can't find any from your documentation about what platforms it is designed for.

**Comment by ecbush** [comment]
The package was developed on Linux, and hasn't been tested on Windows. (I should do that!). It looks to me like your particular problem could be addressed by making a small change in genbank.py. If line 44 were changed from

genbankName = fileName.split("/")[-1]

to

genbankName = fileName.split("\\")[-1]

that might do the trick for you.

(There might be other windows related issues though). I'll try to locate a windows box to test it on myself. But it might take me a few weeks before I can get to it.

I hope this helps,
Eliot

**Comment by ecbush** [comment]
Actually I just updated the repository to do that particular line in a more platform independent way. So you can try pulling that and maybe it will work for you...though as I say there may still be other platform related issues. I'll try to take a look myself in the next few weeks.

**Comment by TysonKlein** [comment]
Thank you, that solved that problem! I'm still getting errors in the analysis portion; would you like me to post them or should I leave this issue open until you get a chance to look at it on a Windows machine?

**Comment by ecbush** [comment]
It doesn't hurt to post it. That might make it a little faster for me to find the problems.
thanks,
Eliot

**Comment by TysonKlein** [comment]
C:\Users\Nicole\Documents\XenoGI\xenoGI-master\example>python -i C:\Users\Nicole\Documents\XenoGI\xenoGI-master/runAnalysis.py params.py

Traceback (most recent call last):
  File "C:\Users\Nicole\Documents\XenoGI\xenoGI-master/runAnalysis.py", line 98, in <module>
    islandByNodeL=islands.readIslands(paramD['islandOutFN'],tree,strainStr2NumD)
  File "C:\Users\Nicole\Documents\XenoGI\xenoGI-master\islands.py", line 312, in readIslands
    f=open(islandFN,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'islands.out'

Thanks!

**Comment by ecbush** [comment]
I've made a few changes to the repository, and run it successfully on Windows now. Give it a try and tell me if it works for you,
best,
Eliot

**Comment by TysonKlein** [comment]
I got my hands on a Linux machine, but I'm still getting the same error on it and on my Windows with the new repository. Is this issue on my end?

**Comment by ecbush** [comment]
Yes, it seems like its not windows specific. Maybe it's on your end?
The error you quoted above makes it seem like some earlier steps didn't happen. To be clear, are you sitting in the example directory and running these 4 things before runAnalysis.py? 

python3 ../parseGenbank.py params.py
python3 ../runBlast.py params.py
python3 ../calcScores.py params.py
python3 ../xenoGI.py params.py

'islands.out' is something that's produced by xenoGI.py.

I'd be happy to carry this on over email...
best,
Eliot
