### ISSUE TITLE
Can you make this `pip installable` ?

### ISSUE THREAD

**Issue by tseemann** [ecbush/xenoGI#2]
It would be great to be able to `pip install xenoGI`.

Any plans?

**Comment by ecbush** [comment]
I hadn't been planning to--however it does seem like its worth taking a look at.

It will probably take a month or two before I can get to it though.

Thanks for the suggestion,
Eliot

**Comment by tseemann** [comment]
Making your software easily installable is critical to getting people to use it, so I look forward to it. I'm told it's not as difficult as it might seem.

**Comment by ecbush** [comment]
Since this is more of a feature request than an issue, I'm going to close it.

**Comment by tseemann** [comment]
Err - normally you would tag it with the label `Enhancement` and leave it open, otherwise you will forget to address it.

**Comment by ecbush** [comment]
I've now made xenoGI pip installable. Thanks for the suggestion.
