### ISSUE TITLE
IndexError: list index out of range（xenoGI）

### ISSUE THREAD

**Issue by littletat** [ecbush/xenoGI#4]
I can successfully run the data in the example.but when I using xenoGI to predict GI in 70 bacterial genomes,meet a problem like this：
"Traceback (most recent call last):
  File "/public/home/jkyin/miniconda2/envs/xenoGI1/bin/xenoGI", line 10, in <module>
    sys.exit(main())
  File "/public/home/jkyin/miniconda2/envs/xenoGI1/lib/python3.6/site-packages/xenoGI/xenoGI.py", line 50, in main
    makeIslandsWrapper(paramD)
  File "/public/home/jkyin/miniconda2/envs/xenoGI1/lib/python3.6/site-packages/xenoGI/xenoGI.py", line 168, in makeIslandsWrapper
    locusIslandByNodeLMerged = islands.makeLocusIslands(geneOrderT,geneNames,subtreeL,tree,paramD,familiesO,strainStr2NumD,strainNum2StrD,islandFormationSummaryF)
  File "/public/home/jkyin/miniconda2/envs/xenoGI1/lib/python3.6/site-packages/xenoGI/islands.py", line 57, in makeLocusIslands
    locIslByNodeL = updateIslandByNodeLEntries(locIslByNodeL,focalNodesL,mergedL)
  File "/public/home/jkyin/miniconda2/envs/xenoGI1/lib/python3.6/site-packages/xenoGI/islands.py", line 220, in updateIslandByNodeLEntries
    locIslByNodeL[clusterL[0].mrca].extend(clusterL)
IndexError: list index out of range"

**Comment by ecbush** [comment]
I can see that clusterL is unexpectedly an empty list here. I'd be interested to figure out why (could be a bug). Is there any chance you could send me the data and let me try running it here? Feel free to email me directly: bush at hmc dot edu.

**Comment by ecbush** [comment]
I pushed a small fix to the master branch which I think should solve your problem. I'll be interested to know if it does. I think this happened in a case where there were no islands on a branch--it would be nice to confirm that though.

**Comment by littletat** [comment]
Thank you very much for your help, I will try it and then tell you the result.

**Comment by littletat** [comment]
Thanks again for your help, I have completed xenoGI in my work. I also have a small suggestion. In the blast step, the “Ralstonia_solanacearum_YC45-Ralstonia_solanacearum_YC45.out” file was generated, but the "-" symbol may be present in the names of strains, which may cause error when split two names. I think if you change to other symbols appear less in the name , might be able to avoid same problems.
erro like this“File "/public/home/jkyin/miniconda2/envs/xenoGI1/lib/python3.6
/site-packages/xenoGI/Score.py", line 94, in getBlastFnByPairD
    strain1,strain2 = os.path.splitext(os.path.split(fileStr)[-1
])[0].split('-')
ValueError: too many values to unpack (expected 2)”

**Comment by ecbush** [comment]
I'm glad it worked. And thank you for the suggestion, that is a good idea.
