### ISSUE TITLE
error in genbank file "lacks protein annotations".

### ISSUE THREAD

**Issue by sky-phenix** [ecbush/xenoGI#6]
I had successfully ran the test data provided along with the the source code. However, when I tried to analyse my data of interest, it shows error as follows,
```
raise ValueError('Some genbank files have problems with their annotations. They are listed in ' + paramD['problemGenbankFN'] + '. Please remove and run again.\n')
ValueError: Some genbank files have problems with their annotations. They are listed in problemGenbankFiles.txt. Please remove and run again.
```
I have used prokka and RAST annotated genbank files, but both annotated files return the same error as above mentioned.

I have a query, Is it possible to include draft genome sequences for this analysis? 

Please help me to fix this issue

**Comment by ecbush** [comment]
hi sky-phenix,

Let me take the draft genome sequence question first. The thing that xenoGI needs is for the assembly to be good enough that it's got scaffolds or better. (needed for the synteny info). So draft genomes may not work well.

In terms of your error. We think this is an issue that arises when there's an ambiguity in the annotations (when an annotation comes up against a contig boundary).

If we're right, one work around for you would be to set 

dnaBasedGeneTrees = False

in the parameter file. In this case, gene trees will be made using protein sequence. (This would not be a good idea for you if your genomes are very closely related though).

In terms of a longer term solution, it would help me if you could provide me with the genbank files that are causing problems. Could you contact me directly via email with that?

thanks,
Eliot

**Comment by sky-phenix** [comment]
Thank you @ecbush , for your prompt response on my request. I had sent you my datasets to you by e.mail, kindly do the needful.

**Comment by sky-phenix** [comment]
Thank you @ecbush , for your prompt response on my request. I had sent you my datasets, kindly do the needful.

**Comment by sky-phenix** [comment]
@ecbush As you mentioned in your e.mail its the problem with my tree file. Now it works well. Thank you for your time and support.
