### ISSUE TITLE
No such file or directory: 'aabrhHardCore.out'

### ISSUE THREAD

**Issue by yl030** [ecbush/xenoGI#8]
Hello xenoGI team,

I installed xenoGI through bioconda and when I run % xenoGI params.py calcScores,  I get this.

/home/.lsbatch/1720416962.695010.shell: line 9: 129947 Killed                  xenoGI params.py calcScores
Traceback (most recent call last):
  File "/home/.conda/envs/xenogi1/bin/xenoGI", line 10, in <module>
    sys.exit(main())
  File "/home/.conda/envs/xenogi1/lib/python3.10/site-packages/xenoGI/xenoGI.py", line 49, in main
    makeSpeciesTreeWrapper(paramD)
  File "/home/.conda/envs/xenogi1/lib/python3.10/site-packages/xenoGI/xenoGI.py", line 181, in makeSpeciesTreeWrapper
    aabrhHardCoreL = scores.loadOrthos(paramD['aabrhFN'])
  File "/home/.conda/envs/xenogi1/lib/python3.10/site-packages/xenoGI/scores.py", line 236, in loadOrthos
    f= open(aabrhFN,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'aabrhHardCore.out'

**Comment by ecbush** [comment]
Unfortunately I'm about to go on vacation, and won't be able to look at this till August. However, it would help to know a few things when I get back.

Could you reply via email (bush@hmc.edu)?

- Are you working with the test dataset?
- Did you already run parseGenbank and runBlast?
- Have you tried runAll?
- Are you on linux?

I'm a bit surprised by the fact that makeSpeciesTreeWrapper is being called, as "xenoGI params.py calcScores" shouldn't do that. The file it's complaining about 'aabrhHardCore.out', is made by calcScores.

best,
Eliot

**Comment by yl030** [comment]
Thanks ecbush!
I installed xenoGI through manual installation, and the code is functioning properly.

**Comment by ecbush** [comment]
Great, thanks for updating me!
